### ISSUE TITLE
Error on post as a Guest

### ISSUE THREAD

**Issue by jakoujan** [saurabhd/octobercms-plugin#2]
Hi Saurabh,

I'm trying to install your plugin but error happend when i'm trying to post message as a guest

this is the error: "Class 'Auth' not found" on line 99 of /home/user/page/plugins/saurabhdhariwal/comments/components/Comments.php"

please help me with this issue.

**Comment by Zmove** [comment]
See that the issue is closed, did you find a solution, I encountered the same problem...
