### ISSUE TITLE
"The author may only contain letters."

### ISSUE THREAD

**Issue by robndg** [saurabhd/octobercms-plugin#3]
When a user is logged in it gives me the error "The author may only contain letters."

I assume Rainlab generates usernames with numbers at the end. So how do we work around this?

**Comment by greinbold** [comment]
Same issue here. How to work with a logged in user when guest are not allowed to comment?

**Comment by greinbold** [comment]
I proposed a PR to fix this problem.

**Comment by saurabhd** [comment]
@greinbold PR Merged. Thanks!
